spring.application.name=customer-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/creditpulse_db
spring.datasource.username=creditpulse_user
spring.datasource.password=creditpulse_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=creditpulse-group
spring.kafka.consumer.auto-offset-reset=earliest


spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.properties.spring.json.value.default.type=com.creditpulse.customerservice.event.CustomerEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*