spring.application.name=customer-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/creditpulse_db
spring.datasource.username=creditpulse_user
spring.datasource.password=creditpulse_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true